name: Tests composite action 

on: 
  # Allows it to be run manually and be reuseable
  workflow_dispatch:
  workflow_call:

jobs:
  CompAction_with_input:
    
    #make sure we have our runner up and going
    runs-on: self-hosted
    name: A job testing composite action
    steps:
      - uses: actions/checkout@v3
      - name: Composite action with string given
        id: travis
        uses: tjvkroll/Bootcamp_composite_actions@main
        with:
          name-to-use: 'Travis'
      - run: echo ${{ steps.travis.outputs.final-string }} >> my-string.txt
      - uses: actions/upload-artifact@v3
        with:
          name: my-string
          path: my-string.txt
          
          
      # Here I'm testing the default nature of my composite action by providing no string to the action
      - name: Composite action without string given
        id: no_input
        uses: tjvkroll/Bootcamp_composite_actions@main
      - run: echo ${{ steps.no_input.outputs.final-string }} >> no-input-string.txt
      # save my artifact to be used in subseqent jobs 
      - uses: actions/upload-artifact@v3
        with: 
          name: no-input
          path: no-input-string.txt
      

  Using_string_with_matrix_strategy:
    strategy:
      matrix:
        values: [1,2,3,4,5,6,7,8,9,10]
    
    runs-on: self-hosted
    name: printing our string with matrix strategy
    needs: CompAction_with_input
    
    steps: 
      - name: downloading all artifacts to be used for printing
        uses: actions/download-artifact@v3
        with:
          path: howdy/
          
      - name: displaying given string from artifact
        shell: bash
        run: |
          value=`cat ~/howdy/my-string.txt`
          echo $value ${{ matrix.values }}
      
      - name: Displaying no input string from artifact
        shell: bash
        run: |
          value='cat ~/howdy/no-input-string.txt'
          echo $value ${{ matrix.values }}
          
      
  
