name: Tests composite action 

on: 
  # Allows it to be run manually and be reuseable
  workflow_dispatch:
  workflow_call:

jobs:
  CompAction_with_input:
    
    #make sure we have our runner up and going
    runs-on: self-hosted
    name: A job testing composite action
    steps:
      - uses: actions/checkout@v3
      - id: travis
        uses: tjvkroll/Bootcamp_composite_actions@main
        with:
          name-to-use: 'Travis'
      - run: echo ${{ steps.travis.outputs.final-string }} >> my-string.txt
      - uses: actions/upload-artifact@v3
        with:
          name: my-string
          path: string.txt

  Using_string_with_matrix_strategy:
    strategy:
      matrix:
        values: [1,2,3,4,5,6,7,8,9,10]
    
    runs-on: self-hosted
    name: printing our string with matrix strategy
