# This is a basic workflow to help you get started with Actions

name: Exercise 1 github actions

# Controls when the workflow will run
on:
  # Enables the workflow to be triggered manually
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "simple"
  simple:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo ${{ secrets.PASSWORD }} 
        
  # Seetting up a string output to be used in subsequent jobs
  string_output_setup:
    
    runs-on: self-hosted
    
    # creates a variable to store our string and where it will be assigned from 
    outputs:
      output1: ${{ steps.step1.outputs.string }} 
    
    # generating the data for our variable that will be output to be used in subsequent jobs
    steps:
      - name: Setting string content  
        id: step1
        run: echo "string=Howdy Doody" >> $GITHUB_OUTPUT
    
  # Uses matrix strategy to output our string on 10 different runners
  printing_output_variable:
    runs-on: self-hosted
    strategy:
      matrix:
        values: [1,2,3,4,5,6,7,8,9,10]
      
    needs: string_output_setup
    steps:
      - env:
          OUTPUT1: ${{needs.string_output_setup.outputs.output1}}
        run: echo "$OUTPUT1 ${{ matrix.values }}"





