# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Enables the workflow to be triggered manually
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "simple"
  simple:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo ${{ secrets.PASSWORD }} 
        
  # Seetting up a string output to be used in subsequent jobs
  string_output_setup:
    
    runs-on: ubuntu-latest
    
    # creates a variable to store our string and where it will be assigned from 
    outputs:
      output1: ${{ steps.step1.outputs.string }} 
    
    # generating the data for our variable that will be output to be used in subsequent jobs
    steps:
      - name: Setting string content  
        id: step1
        run: echo "string=Howdy Doody" >> $GITHUB_OUTPUT
    
    #
  printing_output_variable:
    runs-on: self-hosted
    strategy:
      matrix:
        values: [1,2,3,4,5,6,7,8,9,10]
      
    needs: string_output_setup
    steps:
      - env:
          OUTPUT1: ${{needs.string_output_setup.outputs.output1}}
        run: echo "$OUTPUT1 ${{ matrix.values }}"




# Exercise 1 tasks:
# 1 Add a trigger to manually run the workflow
# 2 Take our password here and put it into a secret and replace it in the workflow with the correct reference
# 3 Create an additional job that will create a simple string output to use in subsequent jobs
# 4 Create another additional job that uses a matrix strategy and will print "<output from previous job>-<numbers 1-10, one at a time>"

# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     # Map a step output to a job output
#     outputs:
#       output1: ${{ steps.step1.outputs.test }}
#       output2: ${{ steps.step2.outputs.test }}
#     steps:
#       - id: step1
#         run: echo "::set-output name=test::hello"
#       - id: step2
#         run: echo "::set-output name=test::world"
#   job2:
#     runs-on: ubuntu-latest
#     needs: job1
#     steps:
#       - env:
#           OUTPUT1: ${{needs.job1.outputs.output1}}
#           OUTPUT2: ${{needs.job1.outputs.output2}}
#         run: echo "$OUTPUT1 $OUTPUT2"
